module Constants
  DEFAULT_JOB_RETRIES = 5
  DEFAULT_CROSSPOST_MAX_ATTEMPTS = 6
  DEFAULT_CROSSPOST_TIMEOUT_DURATION = 10.minutes
  CROSSPOST_PUBLISH_FINISHING_DELAY = 30.seconds
  CROSSPOST_PUBLISH_FINISHING_LIMIT = 24.hours
  LINKEDIN_RENEWAL_WINDOW_DAYS = 10
  LINKEDIN_REMINDER_COOLDOWN_HOURS = 24
  YOUTUBE_RENEWAL_WINDOW_DAYS = 0
  YOUTUBE_REMINDER_COOLDOWN_HOURS = 24

  DEFAULT_POST_CONSTRAINTS = {
    character_limit: 10000,
    counter: ->(content) { content.size },
    hashtag_pattern: Patterns::HASHTAG,
    url_pattern: Patterns::URL
  }.freeze
end
