require "test_helper"

class BlocksAutogeneratedCrosspostTest < ActiveSupport::TestCase
  def setup
    @feed = feeds(:user_feed)
    @account = accounts(:user_x_account)
    @subject = BlocksAutogeneratedCrosspost.new
  end

  def test_blocks_when_feed_id_present_as_integer
    @account.update!(disabled_feed_ids: [@feed.id])
    assert @subject.block?(account: @account, feed_id: @feed.id)
  end

  def test_blocks_when_feed_id_present_as_string
    @account.update!(disabled_feed_ids: [@feed.id.to_s])
    assert @subject.block?(account: @account, feed_id: @feed.id)
  end

  def test_allows_when_feed_id_not_present
    @account.update!(disabled_feed_ids: [])
    refute @subject.block?(account: @account, feed_id: @feed.id)
  end

  def test_allows_when_account_or_list_is_nil
    assert_equal false, @subject.block?(account: nil, feed_id: @feed.id)
    # Do not persist nil due to NOT NULL; just set in-memory to simulate
    @account.disabled_feed_ids = nil
    assert_equal false, @subject.block?(account: @account, feed_id: @feed.id)
  end
end
