class FetchesFeed
  class CreatesCrossposts
    def initialize
      @blocks_autogenerated_crosspost = BlocksAutogeneratedCrosspost.new
    end

    def create!(feed, published_after: nil, skip_posts_older_than: nil)
      return unless feed.automatically_create_crossposts?

      accounts = feed.user.accounts.select { |account| account.active? && !account.manually_create_crossposts? }
      posts = feed.posts.where(crossposts_created_at: nil)

      Feed.transaction do
        posts.each do |post|
          status = status_for_post(post, first_fetch: published_after.nil?, skip_posts_older_than:)

          accounts.each do |account|
            next if @blocks_autogenerated_crosspost.block?(account: account, feed_id: feed.id)
            Crosspost.create!(account: account, post: post, status: status)
          end
        end

        posts.update_all(crossposts_created_at: Now.time)
      end
    end

    def status_for_post(post, first_fetch:, skip_posts_older_than:)
      if first_fetch
        "skipped"
      else
        post_timestamp = post_chronological_timestamp(post)
        if post_timestamp.nil? || skip_posts_older_than.nil? || post_timestamp >= skip_posts_older_than
          "ready"
        else
          "skipped"
        end
      end
    end

    private

    def post_chronological_timestamp(post)
      post.remote_published_at || post.remote_updated_at || post.created_at
    end
  end
end
