#!/usr/bin/env bash
set -euo pipefail

if [[ "${RAILS_ENV:-development}" == "production" ]]; then
  exec bundle exec puma -C config/puma.rb
else
  exec env WEB_THREADS=${WEB_THREADS:-3} bin/rails server -p 3000 -b 0.0.0.0
fi
